#!/bin/bash
# Homebrew: Brewfile with taps, explicitly installed formulae, casks and App Store apps.

backup_brew() {
  info "Homebrew"
  require_cmd brew "Install it from https://brew.sh"
  local out="$DATA_DIR/Brewfile" tmp taps formulae casks mas_apps desc_f desc_c t f c
  tmp="$(mktemp)"
  taps="$(brew tap)"
  formulae="$(brew list --installed-on-request)"
  casks="$(brew list --cask -1 2>/dev/null || true)"
  mas_apps="$(collect_mas_apps)"
  # shellcheck disable=SC2086
  desc_f="$(brew desc $formulae 2>/dev/null || true)"
  # shellcheck disable=SC2086
  desc_c="$([ -n "$casks" ] && brew desc --cask $casks 2>/dev/null || true)"

  {
    echo "# Brewfile generated by macbackup on $(hostname -s)."
    echo "# Only formulae that were installed on request are listed; Homebrew resolves their dependencies."
    echo "# Restore with: brew bundle install --file=Brewfile"
    echo
    for t in $taps; do echo "tap \"$t\""; done
    if [ -n "$mas_apps" ] && ! printf '%s\n' "$formulae" | grep -qx mas; then echo 'brew "mas"'; fi
    for f in $formulae; do echo "brew \"$f\"$(brew_desc_comment "$f" "$desc_f")"; done
    for c in $casks; do echo "cask \"$c\"$(brew_desc_comment "$c" "$desc_c")"; done
    printf '%s\n' "$mas_apps" | while IFS=$'\t' read -r id name; do
      [ -n "$id" ] && echo "mas \"$name\", id: $id"
    done
  } > "$tmp"
  mv "$tmp" "$out"

  fresh_dir "$DATA_DIR/brew"
  brew list --formula --versions > "$DATA_DIR/brew/formulae-including-dependencies.txt"
  brew list --cask --versions > "$DATA_DIR/brew/casks.txt" 2>/dev/null || true
  ok "$(printf '%s\n' "$formulae" | grep -c .) formulae, $(printf '%s\n' "$casks" | grep -c .) casks, $(printf '%s\n' "$mas_apps" | grep -c .) App Store apps"
}

collect_mas_apps() {
  # App Store apps as "id<TAB>name", from mas (needs Spotlight metadata) and from receipts (needs network).
  {
    if command -v mas >/dev/null 2>&1; then
      mas list 2>/dev/null | sed -n 's/^\([0-9][0-9]*\)[[:space:]][[:space:]]*\(.*[^[:space:]]\)[[:space:]][[:space:]]*(.*)$/\1\t\2/p'
    fi
    mas_apps_from_receipts
  } | sort -t "$(printf '\t')" -k1,1 -u | sort -t "$(printf '\t')" -k2
}

mas_apps_from_receipts() {
  # Spotlight often lacks the receipt metadata mas relies on; resolve receipt-bearing apps via the lookup API instead.
  local app bundle cache="$MACBACKUP_STATE_DIR/mas-lookup" json id name
  mkdir -p "$cache"
  for app in /Applications/*.app "$HOME"/Applications/*.app; do
    [ -e "$app/Contents/_MASReceipt/receipt" ] || continue
    bundle="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$app/Contents/Info.plist" 2>/dev/null)" || continue
    if [ -s "$cache/$bundle" ]; then cat "$cache/$bundle"; continue; fi
    json="$(curl -fsS --max-time 15 "https://itunes.apple.com/lookup?bundleId=$bundle&entity=macSoftware" 2>/dev/null | tr -d '\n')"
    id="$(printf '%s' "$json" | sed -n 's/.*"trackId":\([0-9][0-9]*\).*/\1/p')"
    name="$(printf '%s' "$json" | sed -n 's/.*"trackName":"\([^"]*\)".*/\1/p')"
    if [ -n "$id" ] && [ -n "$name" ]; then
      printf '%s\t%s\n' "$id" "$name" | tee "$cache/$bundle"
    else
      warn "App Store app $(basename "$app" .app) ($bundle) could not be resolved to an App Store id"
    fi
  done
}

brew_desc_comment() {
  # brew_desc_comment <name> <brew desc output> -> "  # description" or nothing
  local desc
  desc="$(printf '%s\n' "$2" | awk -v n="$1" 'index($0, n ": ") == 1 { print substr($0, length(n) + 3); exit }')"
  [ -n "$desc" ] && printf '  # %s' "$desc"
  return 0
}

brewfile_entry_count() {
  grep -cE '^(brew|cask|mas) ' "$1" 2>/dev/null || echo 0
}

restore_brew() {
  local file="$DATA_DIR/Brewfile"
  if [ ! -f "$file" ]; then warn "No Brewfile in backup, skipping Homebrew"; return 0; fi
  require_cmd brew "Install it from https://brew.sh"
  info "Homebrew: $(grep -c '^brew ' "$file") formulae, $(grep -c '^cask ' "$file") casks, $(grep -c '^mas ' "$file") App Store apps"
  if grep -q '^mas ' "$file"; then
    log "  App Store apps need you to be signed in to the App Store app before they can install."
  fi
  confirm "Install everything from the Brewfile? (already installed items are skipped)" || return 0
  run brew bundle install --file="$file" --no-upgrade || warn "brew bundle reported errors; re-run 'macbackup restore --only brew' after fixing them"
  return 0
}
